DFE-Digital/manage-courses-support

.travis.yml
Deploy this app like all the other BAT apps (via branches and Travis).
Config for Travis to do this automagically.
=> Configure Travis to deploy to Azure on dev, staging and prod

.travis.yml, README.md, config/database.yml, db/seeds.rb, start.sh
This app doesn't have any documentation on how to set it up for development, nor any test data to get developers going.
* Add a README
* Add some seed test data
=> Make app more dev friendly

app/models/access_request.rb, app/views/access_requests/_access_request.html.erb
The access request view template duplicates some of the same logic as the org view.
DRY up the access request template, using some model changes to line up field names.
=> Refactor view duplication

app/assets/stylesheets/application.scss, app/assets/stylesheets/bar.scss, app/controllers/reports_controller.rb, app/models/course_enrichment.rb, app/models/institution.rb, app/models/institution_enrichment.rb, app/models/nctl_organisation.rb, app/models/organisation.rb, app/models/organisations_engagement_report.rb, app/models/ucas_course.rb, app/views/layouts/application.html.erb, app/views/reports/_stat.html.erb, app/views/reports/show_organisations_engagement_report.html.erb, config/routes.rb, db/schema.rb, db/seeds.rb, spec/factories/factories.rb, spec/features/organisations_engagement_reports_spec.rb, spec/models/organisations_engagement_report_spec.rb
This report helps us measure performance and prioritise on-boarding.
* add a SQL report wrapped in a model
* surface the report on the root URL
* the report is incomplete, more metrics coming in a follow-up PR
=> Organisations engagement report (part 1)

app/assets/stylesheets/bar.scss, app/views/reports/show_organisations_engagement_report.html.erb
2 small visual tweaks to the orgs report
=> Font and copy tweak to the orgs report

app/models/organisations_engagement_report.rb, app/views/reports/show_organisations_engagement_report.html.erb, spec/factories/factories.rb, spec/models/organisations_engagement_report_spec.rb
It's valuable to track what the organisational uptake is for 'About your org' and course enrichment.
Track draft/published states for enrichment, and surface it in the report.
=> Reporting funnel part 2

app/services/manage_courses_api_service.rb, config/initializers/manage_courses_api_service.rb, spec/features/access_requests_spec.rb, spec/models/access_request_spec.rb, spec/services/manage_courses_api_service_spec.rb
The support app can't approve the access requests on dev.
The environment variables are slightly different to what was expected, so this updates the logic around it.
=> Update ManageCoursesAPIService to correctly set URL and Authorization

spec/features/access_requests_spec.rb
A bit of spec restructuring and rewording to make it a bit more idiomatic.
Best reviewed commit-by-commit.
=> Spec improvements

app/controllers/access_requests_controller.rb, app/models/access_request.rb, app/models/emailed_access_request.rb, app/views/access_requests/create.html.erb, app/views/access_requests/preview.html.erb, spec/features/access_requests_spec.rb, spec/models/access_request_spec.rb, spec/models/emailed_access_request_spec.rb
This change consolidates some logic from views and the controller, and allows us to use some Rails convenience methods for generating the forms and reading parameters.
=> Extract emailed access request model

app/views/access_requests/new.html.erb
I don't believe these are valid.
=> Remove classes from closing div tags

app/models/emailed_access_request.rb, app/models/user.rb, app/views/access_requests/preview.html.erb, spec/features/access_requests_spec.rb, spec/models/emailed_access_request_spec.rb
Improve the presentation, remove unnecessary info and add new useful info on the preview screen for emailed requests.
Before:
After:
=> Preview improvements for emailed requests

app/controllers/organisations_controller.rb, app/helpers/organisation_helper.rb, app/models/course.rb, app/models/course_enrichment.rb, app/models/institution.rb, app/models/institution_enrichment.rb, app/models/nctl_organisation.rb, app/models/organisation.rb, app/models/organisations_engagement_report.rb, app/models/ucas_course.rb, app/models/user.rb, db/schema.rb, db/seeds.rb, spec/factories/factories.rb, spec/features/organisations_spec.rb, spec/models/emailed_access_request_spec.rb
The Manage Courses API database [has been re-designed](https://github.com/DFE-Digital/manage-courses-api/pull/201). Since this app connects works directly off that DB, it requires code changes to keep working.
Code and spec changes to ensure the app keeps working when the Manage Courses DB changes are rolled out to production.
=> Schema changes

.travis.yml
To allow us to roll back deployments
=> Add force to deploy push

Gemfile, Gemfile.lock, config.ru
Logging errors on Azure
Add `application_insights`
=> Setup application insights

config/environments/production.rb
Logging
Make logging consistent across all rails apps
=> Update logging for prod

.travis.yml, deploy.sh, scripts/deploy_dev.sh, scripts/deploy_prod.sh, scripts/deploy_staging.sh
Thinking of using this pattern for all the other LocalGit apps.
Feedback please!
=> DRY the deploy scripts

deploy.sh
Sorry for the PR noise, can only test this when it hits travis
=> Fix variable escaping

Gemfile, README.md, azure-pipelines.yml, azure/template.json, docker-compose.az.yml
This PR adds support for azure piplines build and releases
* Add ARM templates to deploy infrastructure
* Add azure-pipelines.yml
* add rspec_junit_formatter gem to enable publishing test results
* Allow multi-file docker-compose builds in az pipelines
Does everything look OK?
=> VSTS build and deploy

azure/template.json
This PR aligns ARM template conventions with our guidelines and preferred styles
* Update template variables
* Add resourceEnvironment and serviceName parameters
=> align conventions

Gemfile, Gemfile.lock, README.md
Setup Sentry
Add Sentry gem and readme instructions
`SENTRY_DSN=URL_FROM_SENTRY_UI rails server`
=> Setup sentry

config/database.yml, config/environments/qa.rb, config/environments/staging.rb, config/webpacker.yml
Setup proper `staging` and `qa` environments
- Add environment config (same as production)
- Add database configs
- Add webpack configs
N/A
=> [1224] Setup qa and staging environment

lib/tasks/create_dev_user.rake
`rake db:setup` was failing for me
update user in setup rake task to match user in database.yml
:ship:
=> Make db setup user match expectation in database.yml

README.md
Yarn is part of the setup but it's not immediately obvious how to install it
Update the readme
:ship:
=> Add yarn to pre-requisites in readme

Rakefile, lib/tasks/govuk_lint.rake
Copied from frontend
Usage:
bundle exec rake lint:ruby
Source: https://github.com/DFE-Digital/manage-courses-frontend/blob/1f7aabc3014c0962e76227aec359893b3de3c7f7/lib/tasks/govuk_lint.rake#L3
=> Add lint rake task

azure/template.json
Appsetting key `SETTINGS__AUTHENTICATION__SECRET`
Added the azure related settings for creds for backend
related to https://github.com/DFE-Digital/bat-infrastructure/pull/124
@OutKa5t @smneal fyi
=> [1363] Added the azure related settings for creds for backend

config/database.yml, config/environments/new_qa.rb, config/webpacker.yml
Add configs to support new QA env
Add configs for new QA env
=> Added new QA env configs

azure/template.json
`SETTINGS__AUTHENTICATION__SECRET`
`SETTINGS__AUTHENTICATION__SECRET`
renamed to 
`SETTINGS__MANAGE_BACKEND__SECRET` for the consumer end
You need approve the respective PR as well as this one
=> [1440] Fixed aligned secrets

config/initializers/authentication.rb
Existing code raised error when env was qa
=> [1363] Allow qa environment when loading config

app/models/access_request.rb, db/seeds.rb, spec/models/access_request_spec.rb
Access requests are missing some user data
Fix up the association between access_requests and users
`/access-requests`
=> [XXXX] Hotfix for missing last_name

.travis.yml, Rakefile, azure-pipelines.yml, bin/rake, docker-compose.az.yml, lib/tasks/govuk_lint.rake
Fixing Docker Hub connectivity issues and failing linter task
Use rake
Align docker tasks to FE/BE
=> Update build tasks

config/settings/new_qa.yml
Add missing rails env to align dev
Rails env yml file
=> Add new QA (ADO dev) yml

azure-pipelines.yml, config/settings/qa.yml, docker-compose.az.yml
Reduce build time by implementing layer caching
Add task to push master builds as latest tags
Add task to pull latest tag for each build
=> Implement layer caching

azure/template.json
Add resource deployment to ensure ASP outbound IP's are added to the relevant PostgreSQL firewall rules
- Add firewall rule resource deployment
- Add databaseServiceName name parameter and related variables
- Formatted document so styling is consistent
=> Add firewall rule resource, params, vars

config/database.yml, config/environments/new_staging.rb, config/settings/new_staging.yml, config/webpacker.yml
Add config bits for new staging env
Add config for database, rails env and webpacker
=> Add new staging env and settings

config/database.yml, config/settings/new_prod.yml
Add config bits for new production env
Add config for database and rails env
- updated database.yml file
- created config/settings/new_prod.yml file
=> Added new production environment config in .yml files

app/views/access_requests/_access_request.html.erb, app/views/access_requests/index.html.erb, spec/features/access_requests_spec.rb
Better info for the support console.
Add the field.
:shipit:
=> [1750] Add organisation column to AR table

config/settings/new_qa.yml, config/settings/new_staging.yml, config/settings/qa.yml
Use service domain urls in app setting yml files
Change dev, qa and staging app settings values for MCSPT to use service domain addresses
=> Updated app settings values in settings/config/yml files

config/database.yml
This is for the new environment that we are deploying tonight.
=> [1755] Add prod section to database.yml

config/settings/production.yml
=> [2042] Fix prod base URL

config/settings/production.yml
=> [2042] Add backslash to base prod url

azure/template.json
Added an app setting to fix deployment failures during swap slots operation
New app settings for MCSPT app service with value 0
`WEBSITE_SLOT_POLL_WORKER_FOR_CHANGE_NOTIFICATION`
=> [143] Added app settings to fix swap slot failures

package.json, yarn.lock
Addresses security issue identified by Github
https://github.com/DFE-Digital/manage-courses-support/network/alert/yarn.lock/set-value/open
- Upgrade Set-value package
=> Upgrade 'Set-value' package

.gitignore, Gemfile, Gemfile.lock, spec/rails_helper.rb
We want to refactor the support console to avoid hitting the DB directly
SimpleCov library added in order to assist in future refactoring
=> [2464] - Add SimpleCov gem

azure-pipelines.yml, docker-compose.az.yml, docker-compose.yaml
Cleanup and remove references of azure container registry which was used for Travis and az pipelines to co exist.
=> 160 Cleanup azure container registry references

azure/template.json
Change databaseResourceGroup from variable to parameter for MCBE DB change
=> 2317 - Change db rg name from variable to parameter
