DFE-Digital/manage-courses-support

.travis.yml

The Azure deployment added in #5 failed due to an issue with git fetch and using the `--unshallow` flag:
https://travis-ci.org/DFE-Digital/manage-courses-support/builds/422203245
According to the Travis docs, setting `git depth: false` makes the unshallow
git fetch unnecessary:
https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth

Try to fix the Azure deployment by removing the git --depth flag

---

Gemfile
Gemfile.lock

The Azure deploy process runs a `rake assets:precompile` to compile asset. This currently fails because `rake` isn't a production dependency.
Add `rake` to the production set of gems.

Explicitly add rake as it's used by Azure for asset precompilation

---

app/models/organisation.rb
db/seeds.rb
spec/features/organisations_spec.rb

In order to support provider end-users, some DfE admins are attached to their organisations. We don't want to surface those admins in the Organisations view as it's noise.
Filter out admin users on the `users` association of the `Organisation` model.

Filter out admin users in the org index

---

app/assets/javascripts/application.js
app/views/layouts/application.html.erb

Prior to this change, support agents need to know the URLs to the org list and for access requests. This isn't very discoverable.
* Add navigation links into the header
* Include the Design System JS (necessary for the mobile menu to work)

Add header navigation links

---

app/helpers/organisation_helper.rb
spec/features/organisations_spec.rb

Support agents often need to look at an organisation's courses to figure out what's going on. This currently involves copying the institution name and searching for that organisation on 'Publish teacher training courses'.
This link allows the support agent to quickly access the institution courses as God user when they're supporting that organisation's users.

Link to the institution courses on Publish

---

app/helpers/organisation_helper.rb
app/views/organisations/_organisation.html.erb
db/schema.rb
db/seeds.rb
spec/factories/factories.rb
spec/features/organisations_spec.rb
spec/helpers/organisation_helper_spec.rb

When supporting user problems, the DfE Sign-in support console audit log is really valuable to piece together the timeline of what the user did when.
Link out to DfE Sign-in if we've got an id for that user to make that journey a bit easier for the support agent.

Deep-link to DfE Sign-in user audit log if appropriate

---

app/views/layouts/application.html.erb

The title was a hold-over from the GOV.UK design system default layout.

Update title to reflect name of the tool

---

app/views/organisations/_organisation.html.erb

This was introduced when I added the parameter in one place but forgot the other.

Bugfix: show the DfE Sign-in deeplink even if there's only one user

---

app/controllers/organisations_controller.rb
app/views/organisations/index.html.erb
config/routes.rb
db/seeds.rb
spec/factories/factories.rb
spec/features/organisations_spec.rb

Support agents need to easily view which organisations haven't engaged with the service yet, so they can make a decision about whether/who to chase.
Add a separate route for surfacing only organisations without active users.
Organisations view
Organisations without active users

Orgs without active users

---

app/assets/stylesheets/_success_summary.scss
app/assets/stylesheets/application.scss
app/controllers/access_requests_controller.rb
app/models/access_request.rb
app/services/manage_courses_api_service.rb
app/views/access_requests/_access_request.html.erb
app/views/access_requests/_access_request_api_result_banner_error.html.erb
app/views/access_requests/_access_request_api_result_banner_success.html.erb
app/views/access_requests/index.html.erb
config/initializers/manage_courses_api_service.rb
config/routes.rb
spec/features/access_requests_spec.rb
spec/models/access_request_spec.rb
spec/services/manage_courses_api_service_spec.rb

Currently the actioning of access requests is done by only one or two people. This means that they get actioned infrequently and this causes repeat support tickets and user frustration.
This creates an API service to handle the necessary POST request to the Manage API, and appropriate views/banners to display feedback to the user whether the request was successful or not.
Easiest reviewed commit by commit.

Automate access requests

---

app/models/access_request.rb
spec/factories/factories.rb

This makes the code a bit more descriptive and reduces reliance on magic
constants.
There is also a fix here for the approved status (which was previously
assumed to be 1 but is actually 2).

Use enums for access request status

---

app/controllers/access_requests_controller.rb
app/models/access_request.rb
app/services/manage_courses_api_service.rb
app/views/access_requests/_access_request_api_result_banner_success.html.erb
app/views/access_requests/create.html.erb
app/views/access_requests/index.html.erb
app/views/access_requests/preview.html.erb
config/routes.rb
spec/features/access_requests_spec.rb
spec/models/access_request_spec.rb
spec/services/manage_courses_api_service_spec.rb

The team gets a lot of access requests through Zendesk. Currently these go into a spreadsheet and need to be batch-actioned via SQL scripts directly into the production DB. This is an awful and unsafe process.
A new journey to fill in, preview, and submit manual access requests using the new API endpoint.

Create and approve an access request manually

---

README.md
mock_manage_courses_api.ru

This makes it easier to develop features which talk to this API without needing to run it locally.

Add and document a Rack-based mock for Manage Courses API

---

app/models/emailed_access_request.rb
spec/models/emailed_access_request_spec.rb

This prevents copy-paste mistakes when copying names and emails from other sources.

Strip whitespace from emailed access request fields

---

app/controllers/access_requests_controller.rb
app/helpers/dfe_signin_helper.rb
app/helpers/notify_helper.rb
app/helpers/organisation_helper.rb
app/views/access_requests/inform_publisher.html.erb
config/routes.rb
spec/features/access_requests_spec.rb

User support agents need to contact the recipient when they've approved access requests. This new step in the journey reminds them and provides them useful links to do so quickly. It should be possible to automate those steps as well.
Add a new post-approval page.

Post approval for access requests

---

app/models/access_request.rb
app/models/emailed_access_request.rb
app/services/manage_courses_api.rb
config/initializers/manage_courses_api.rb
spec/services/manage_courses_api_service_spec.rb

This word is redundant and the names are more concise without it.

Remove 'service' from class and constant references to Manage Courses API

---

app/controllers/access_requests_controller.rb
spec/features/access_requests_spec.rb

Add missing test coverage that would have caught this failure.

App shouldn't crash when emailed access request API call fails

---

app/views/layouts/application.html.erb

PR #37 added `success_summary` and `error_summary` into the application layout, but they were inadvertently added inside the `content_for :heading` block.
Take the partial calls out of the block so they're always executed.

Success and error summaries were accidentally added in the wrong place

---

app/controllers/access_requests_controller.rb
app/models/access_request.rb
app/services/manage_courses_api.rb
spec/features/access_requests_spec.rb
spec/models/access_request_spec.rb
spec/models/emailed_access_request_spec.rb
spec/services/manage_courses_api_spec.rb

* reduce duplication in the client
* improve the client to handle network failures
* re-engineer the client to use exceptions instead of statuses
Why exceptions instead of statuses:
* any failures in the API calls are exceptional by nature (inconsistent data, misconfiguration of the API, network failures) rather than incorrect actions by end-users.
* exceptions allow packing more info about the failure, closer to the source of the failure so the knowledge is better encapsulated in the API client.

Manage courses API client improvements

---

app/controllers/access_requests_controller.rb
app/models/emailed_access_request.rb
app/views/access_requests/new.html.erb
app/views/application/_error_summary.html.erb
spec/features/access_requests_spec.rb
spec/models/emailed_access_request_spec.rb

When granting emailed access requests, the 'requester email' must exist in the system, and all fields for the recipient information are necessary. Currently the app doesn't do any server-side validation around these things.
* add model validation prior to preview
* show errors to the user when validation fails

Emailed access request validation

---

app/models/emailed_access_request.rb
spec/features/access_requests_spec.rb

The Manage Courses API is case-sensitive (which it probably shouldn't be) and access control expects emails to be lower case.
Downcase the email that the support agent enters before sending it to the API.

Emailed access requests: recipient emails should be lowercase

---

.travis.yml

Prior to this change, we were using a single deployment user for all deploys.
This commit switches to app-specific deployment credentials which should be a safer
approach in case the credentials are compromised.

Switch to using app-specific deployment users

---

README.md

Couldn't get native version to behave. Because node. This is what I had to do to fire up the docker version.

Add docker instructions to readme

---

.rubocop.yml
.travis.yml
Gemfile

The linter wasn't properly configured to use govuk-lint's rules, as on our other apps.
Configure the linter as we do on our other apps.

[1448] Bring linting rules in line with other apps

---

app/models/organisations_engagement_report.rb

This fell over when pointed at the backend development database
because it doesn't seed allocations.

[1363] Cope with no org allocations

---

app/controllers/application_controller.rb
config/settings.yml

https://github.com/DFE-Digital/bat-infrastructure/blob/master/bat/find-courses/manage-courses/terraform.tf#L209
`authentication` > `manage_backend` - we agreed on the terraform side that this was much clearer naming
:ship:

[1363] Bring backend auth config into line with terraform

---

config/initializers/config.rb

Support wasn't reading the backend secret from the azure environment
variables because the `config.rb` for the config gem was missing. Thus all requests to backend approve access requests were failing with a jwt token validation error
> JWT::VerificationError: Signature verification raised
> app/services/authentication_service.rb in decoded_token at line 26
https://github.com/railsconfig/config#working-with-environment-variables
Add copy of https://github.com/DFE-Digital/manage-courses-frontend/blob/master/config/initializers/config.rb
:ship:

[1363] Make support config read from env

---

app/controllers/access_requests_controller.rb
config/settings/development.yml
spec/features/access_requests_spec.rb
spec/models/access_request_api_spec.rb

The support app currently hits the db directly when manually creating an access request. This PR refactors this process so it hits the backend create endpoint.
- Refactors the create method to hit the mcbe create, then approve route.

[1491] Switch support apps manual creation method to hit mcbe #create route

---

app/models/access_request_api.rb
spec/features/access_requests_spec.rb

Index view for displaying access requests was showing the requester email for both the requester and recipient.
Change the recipient email to use the recipients email address

1376 fix recipient email view bug

---

config/settings/new_staging.yml

Update new staging environment to use non-Azure domains
Change base_url value in New_staging.yml file from default azure web app .azurewebsites.net urls to service domains
base_url updated in new_staging.yml file only. New staging service domain urls are as follows:
mcapi: https://api.staging.publish-teacher-training-courses.service.gov.uk
mcbe: https://api2.staging.publish-teacher-training-courses.service.gov.uk
mcfe: https://www2.staging.publish-teacher-training-courses.service.gov.uk
mcspt: https://support.staging.publish-teacher-training-courses.service.gov.uk
mcui: https://www.staging.publish-teacher-training-courses.service.gov.uk
sacapi: https://api.staging.find-postgraduate-teacher-training.service.gov.uk
sacui: https://www.staging.find-postgraduate-teacher-training.service.gov.uk

Updated base_url to use service domain

---

app/helpers/organisation_helper.rb
app/models/emailed_access_request.rb
config/settings/development.yml
config/settings/new_qa.yml
config/settings/new_staging.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml
db/seeds.rb
spec/factories/access_request.rb
spec/features/organisations_spec.rb

All the environments currently link to prod which is asking for mistakes
to be made.
* config for links to publish site
:ship:

Make publish site url configurable

---

app/helpers/organisation_helper.rb
spec/features/organisations_spec.rb

Links on https://bat-qa-mcspt-as.azurewebsites.net/organisations are broken, presumably the urls changed in manage-courses-frontend.
before: https://bat-qa-mcfe-as.azurewebsites.net//organisation/76g (404)
after: https://bat-qa-mcfe-as.azurewebsites.net/organisations/76G

[1927] Fix link to manage courses

---

app/controllers/access_requests_controller.rb

Manual access requests were returning an error due to backend `presence: true` requirements on the `reason` and `organisation` fields.
- Add in default reason and use the requesting users organisations when hitting the backend create endpoint.

[1991] Add reason and organisation to create method
